//! Implementation of the `sandcastle profiles` subcommands.

use anyhow::Context;
use sandcastle_policy::profile::BuiltinProfile;
use sandcastle_policy::resolver::ProfileResolver;

/// All built-in profiles with their display names and descriptions.
static BUILTINS: &[(&str, BuiltinProfile)] = &[
    ("claude-code", BuiltinProfile::ClaudeCode),
    ("codex", BuiltinProfile::Codex),
    ("langchain", BuiltinProfile::LangChain),
    ("ollama", BuiltinProfile::Ollama),
    ("openclaw", BuiltinProfile::OpenClaw),
];

/// List all built-in profiles with their trust levels.
pub fn list() -> anyhow::Result<()> {
    println!("{:<16} {:<14} {}", "NAME", "TRUST LEVEL", "DESCRIPTION");
    println!("{}", "-".repeat(80));

    for (name, builtin) in BUILTINS {
        let profile = builtin.to_profile();
        println!(
            "{:<16} {:<14} {}",
            name,
            format!("{:?}", profile.trust_level).to_lowercase(),
            profile.description,
        );
    }

    println!();
    println!("Use `sandcastle profiles show <name>` for full permission details.");
    println!("Use `sandcastle profiles create <name>` to scaffold a custom profile YAML.");
    Ok(())
}

/// Show detailed information about a named profile.
pub fn show(name: &str) -> anyhow::Result<()> {
    let resolver = ProfileResolver::new(vec![
        std::env::current_dir().unwrap_or_default(),
    ]);

    let p = resolver
        .resolve(name)
        .with_context(|| format!("Profile '{name}' not found. Run `sandcastle profiles list` to see available profiles."))?;

    println!("Profile: {}", p.name);
    println!("  description : {}", p.description);
    println!("  trust_level : {:?}", p.trust_level);
    println!("  audit       : {}", p.audit_enabled);
    println!("  gpu         : {}", p.permissions.gpu.enabled);
    println!();

    println!("Filesystem read:");
    for path in &p.permissions.filesystem.allow_read {
        println!("  + {path}");
    }
    println!("Filesystem write:");
    for path in &p.permissions.filesystem.allow_write {
        println!("  + {path}");
    }
    println!("Filesystem deny:");
    for path in &p.permissions.filesystem.deny {
        println!("  - {path}");
    }
    println!();

    println!("Network allow:");
    for domain in &p.permissions.network.allow_domains {
        println!("  + {domain}");
    }
    println!("Network deny:");
    for domain in &p.permissions.network.deny_domains {
        println!("  - {domain}");
    }
    if let Some(bw) = &p.permissions.network.max_bandwidth {
        println!("  bandwidth cap: {bw}");
    }
    println!();

    println!("Processes allow:");
    for proc in &p.permissions.processes.allow {
        println!("  + {proc}");
    }
    println!("Processes deny:");
    for proc in &p.permissions.processes.deny {
        println!("  - {proc}");
    }
    println!();

    println!("Resource limits:");
    if let Some(cpu) = &p.permissions.resources.max_cpu {
        println!("  cpu          : {cpu}");
    }
    if let Some(mem) = &p.permissions.resources.max_memory {
        println!("  memory       : {mem}");
    }
    if let Some(disk) = &p.permissions.resources.max_disk {
        println!("  disk         : {disk}");
    }
    if let Some(fds) = p.permissions.resources.max_open_files {
        println!("  open_files   : {fds}");
    }

    Ok(())
}

/// Scaffold a new custom profile YAML in the current directory.
pub fn create(name: &str) -> anyhow::Result<()> {
    let file_name = format!("sandcastle.{name}.yaml");
    let path = std::env::current_dir()
        .unwrap_or_default()
        .join(&file_name);

    anyhow::ensure!(
        !path.exists(),
        "Profile file '{}' already exists.",
        path.display()
    );

    let yaml = format!(
        r#"# SandCastle profile: {name}
# Generated by `sandcastle profiles create {name}`
# Trust levels: explore | develop | build | full | unrestricted
name: {name}
description: "Custom profile — adjust permissions as needed"
trust_level: develop
audit_enabled: true
permissions:
  filesystem:
    allow_read:
      - "$PROJECT_DIR/**"
      - "~/**"
    allow_write:
      - "$PROJECT_DIR/**"
    deny:
      - "/etc/**"
      - "/sys/**"
      - "/proc/**"
      - "~/.ssh/**"
      - "~/.gnupg/**"
      - "~/.aws/**"
  network:
    allow_domains:
      - "github.com"
      - "*.github.com"
    deny_domains: []
    # max_bandwidth: "50Mbps"
  processes:
    allow:
      - "git"
    deny:
      - "sudo"
      - "su"
  resources:
    max_cpu: "100%"
    max_memory: "4GB"
    max_disk: "10GB"
    max_open_files: 1024
  gpu:
    enabled: false
    devices: []
"#
    );

    std::fs::write(&path, yaml)
        .with_context(|| format!("Failed to write '{}'", path.display()))?;

    println!("Created '{}'", path.display());
    println!("Edit the file, then validate it with:");
    println!("  sandcastle policy validate {file_name}");
    println!("Run with:");
    println!("  sandcastle run --profile {name} -- <command>");

    Ok(())
}
